version: '3'

services:
  valerio-nginx:
    image: valerio-nginx
    container_name: valerio-nginx-compose
    ports:
      - '8080:80'
    networks:
      - valerio-network

  valerio-backend:
    image: valerio-backend
    container_name: valerio-backend-compose
    depends_on:
      - valerio-nginx
    ports:
      - '8000:8000'
    networks:
      - valerio-network

  valerio-frontend:
    image: valerio-frontend
    container_name: valerio-frontend-compose
    depends_on:
      - valerio-backend
    ports:
    - '4173:4173'
    networks:
      - valerio-network

networks:
  valerio-network:
    driver: bridge
